### PR TITLE
chore: update main with develop

### PR DESCRIPTION
**Pull request by JustSamuel**
# Description
Main features are the RBAC in the database, and reports to pdf functionality.

## Types of changes

- Bug fix _(non-breaking change which fixes an issue)_
- New feature _(non-breaking change which adds functionality)_

### CODE REVIEW

**Review by Yoronex — APPROVED** [review]

**Comment by SuperVK** [comment]
https://github.com/GEWIS/sudosos-backend/pull/203 is a breaking pull request so we should wait before we know how we are going to deal with this

**Comment by JustSamuel** [comment]
> #203 is a breaking pull request so we should wait before we know how we are going to deal with this

?

**Comment by SuperVK** [comment]
> > #203 is a breaking pull request so we should wait before we know how we are going to deal with this
> 
> ?

It changes the return type of an endpoint from PaginatedResult to just an array

**Comment by JustSamuel** [comment]
ah check, get it. You meant that it would break production.

**Comment by JustSamuel** [comment]
> this issue (the breaking change) already been resolved?

Well, its a intended change though. We just have to update it on dev and make sure the FE isready when updating main.

**Comment by Yoronex** [comment]
@SuperVK has this breaking change already been implemented in the FE? I would like to update main so I can work on stuff like the pricelist on barcommissie.nl (for which the new RBAC system would really help).

**Comment by SuperVK** [comment]
We cant fix it, because it first requires a change in the sudosos-client, which in turn requires this PR to be merged. (This should have been a v2 in the api ideally) So I propose to merge this, and quickly fix the FE. But I am on holiday till next week Saturday, so hopefully somebody else can pick it up?

**Comment by JustSamuel** [comment]
> We cant fix it, because it first requires a change in the sudosos-client, which in turn requires this PR to be merged. (This should have been a v2 in the api ideally) So I propose to merge this, and quickly fix the FE. But I am on holiday till next week Saturday, so hopefully somebody else can pick it up?

Can't we just use the client of the development branch?

**Comment by SuperVK** [comment]
Yeah read that only after, should work yeah

**Pull request merged**
