### PR TITLE
fix: retry test case to fix flaky test

### PR DESCRIPTION
**Pull request by JustSamuel**
# Description
Test cases has a tendency to fail.

## Types of changes
- CI/CD _(Changes to the CI/CD configuration)_

### CODE REVIEW

**Comment by Yoronex** [comment]
Any idea why the test case sometimes fails?

**Comment by Yoronex** [comment]
Can you send me more details, for example where it fails and with what reason? I have never seen this test case fail.

**Comment by Yoronex** [comment]
Okay I have encountered the issue myself.

image

This seems to happen only in the `test-ci-migrate` tests, which use the database after migrations. The issue is that event answer sheets are not correctly (automatically) deleted by the database, even though they have the SQL relational property `CASCADE`. Any clue what the issue could be? Database still deleting these sheets in the background?

**Comment by JustSamuel** [comment]
I don't think its the `migrate`, see the current dev flow:
image

Maybe you are just to fast? I.E the cascade delete taking longer than the next step to start?

**Comment by Yoronex** [comment]
Not the only test that seems to be flaky...

image

**Comment by JustSamuel** [comment]
Seems to have fixed itself over the course of the last month, closing for now, can be re-opened if found to be an issue again.

**Pull request closed without merging**
