### PR TITLE
feat: extend balance response with extra user attributes

### PR DESCRIPTION
**Pull request by Yoronex**
# Description

Adds extra attributes to `BalanceResponse`, namely `user.firstName`, `user,lastName`, `user.nickname`, `user.type`, and `UserFineGroup.waivedTransfer.amountInclVat` (see https://github.com/GEWIS/sudosos-backend/pull/344).

## Related issues/external references

https://github.com/GEWIS/sudosos-backend/issues/334

## Types of changes

- New feature _(non-breaking change which adds functionality)_

### CODE REVIEW

**Comment by Yoronex** [comment]
@JustSamuel I cannot reproduce the failing test cases on my local machine... Can you maybe try and see whether they fail or pass for you?

**Comment by JustSamuel** [comment]
> @JustSamuel I cannot reproduce the failing test cases on my local machine... Can you maybe try and see whether they fail or pass for you?

No errors on my machine either

**Comment by JustSamuel** [comment]
What was it :o

**Comment by Yoronex** [comment]
Something is going wrong with a seeder, but I have to investigate further. Could be a race condition? Incorrect state update? I don't know...

**Review by JustSamuel — APPROVED** [review]

**Pull request merged**
