### PR TITLE
chore: use TypeORM DataSource to initialize database

### PR DESCRIPTION
**Pull request by Yoronex**
# Description

Still initialize the database, but also expose a `DataSource` object that should be used over `getConnection()`.

## Related issues/external references

Fixes https://github.com/GEWIS/sudosos-backend/issues/68.

## Types of changes

- Bug fix _(non-breaking change which fixes an issue)_
- Style _(Change that do not affect the functionality of the code)_

### CODE REVIEW

**Review by JustSamuel — CHANGES_REQUESTED** [review]
TypeORM doesn't like this since you do not actually export an `instantiated` DataSource object.

Trying to use the CLI gives the following:

`PS C:\Users\Samuel\WebstormProjects\GEWIS\SudoSOS\sudosos-backend> typeorm migration:show -d .\out\src\database\database.js
Error during migration show:
Error: Given data source file must contain export of a DataSource instance
    at CommandUtils.loadDataSource (C:\Users\Samuel\WebstormProjects\GEWIS\SudoSOS\sudosos-backend\node_modules\typeorm\commands\CommandUtils.js:44:19)
    at async Object.handler (C:\Users\Samuel\WebstormProjects\GEWIS\SudoSOS\sudosos-backend\node_modules\typeorm\commands\MigrationShowCommand.js:27:26)
`
That is why I had the `export const AppDataSource = new DataSource(options);`

**Comment by Yoronex** [comment]
But that export that you made was not usable in the actual codebase... When you imported AppDataSource and tried to use it (for example with `getRepository(<entity>)`, the DataSource would never be initialized.

**Comment by JustSamuel** [comment]
> But that export that you made was not usable in the actual codebase... When you imported AppDataSource and tried to use it (for example with `getRepository(<entity>)`, the DataSource would never be initialized.

Yeah, but I believe that is how the CLI needs it ? As I see [here](https://orkhan.gitbook.io/typeorm/docs/data-source) you must always init the AppDataSource

**Comment by Yoronex** [comment]
@JustSamuel can you verify the CLI works now?

**Review by JustSamuel — APPROVED** [review]
Works!

**Pull request merged**
